// Taxonomie de navigation Vinted — chemins exacts pour le bookmarklet et le prompt de reconnaissance
// Format : "N1 > N2 > N3 [> N4 [> N5]]"
// Source : interface Vinted FR — à mettre à jour si Vinted modifie sa navigation

export const NAV_PATHS: readonly string[] = [

  // ── FEMMES > VÊTEMENTS ──────────────────────────────────────────────────
  'Femmes > Vêtements > Manteaux et vestes > Capes et ponchos',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Duffle-coats',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Manteaux en fausse fourrure',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Pardessus et manteaux longs',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Parkas',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Cabans',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Imperméables',
  'Femmes > Vêtements > Manteaux et vestes > Manteaux > Trenchs',
  'Femmes > Vêtements > Manteaux et vestes > Vestes sans manches',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Perfectos et blousons de moto',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Blousons aviateur',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes en jean',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes militaires et utilitaires',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes polaires',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Doudounes',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes matelassées',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes chemises',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes de ski et snowboard',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Blousons teddy',
  'Femmes > Vêtements > Manteaux et vestes > Vestes > Vestes coupe-vent',

  'Femmes > Vêtements > Sweats et sweats à capuche > Sweats & sweats à capuche',
  "Femmes > Vêtements > Sweats et sweats à capuche > Sweats > Pulls col V",
  "Femmes > Vêtements > Sweats et sweats à capuche > Sweats > Pulls col roulé",
  'Femmes > Vêtements > Sweats et sweats à capuche > Sweats > Sweats longs',
  "Femmes > Vêtements > Sweats et sweats à capuche > Sweats > Pulls d'hiver",
  'Femmes > Vêtements > Sweats et sweats à capuche > Sweats > Sweats manche ¾',
  'Femmes > Vêtements > Sweats et sweats à capuche > Sweats > Autres sweats',
  'Femmes > Vêtements > Sweats et sweats à capuche > Kimonos',
  'Femmes > Vêtements > Sweats et sweats à capuche > Cardigans',
  'Femmes > Vêtements > Sweats et sweats à capuche > Boléros',
  'Femmes > Vêtements > Sweats et sweats à capuche > Vestes',
  'Femmes > Vêtements > Sweats et sweats à capuche > Autres pull-overs & sweat-shirts',

  'Femmes > Vêtements > Blazers et tailleurs > Blazers',
  'Femmes > Vêtements > Blazers et tailleurs > Ensembles tailleur/pantalon',
  'Femmes > Vêtements > Blazers et tailleurs > Jupes et robes tailleurs',
  'Femmes > Vêtements > Blazers et tailleurs > Tailleurs pièces séparées',
  'Femmes > Vêtements > Blazers et tailleurs > Autres ensembles & tailleurs',

  'Femmes > Vêtements > Robes > Mini',
  'Femmes > Vêtements > Robes > Midi',
  'Femmes > Vêtements > Robes > Robes longues',
  'Femmes > Vêtements > Robes > Pour occasions',
  "Femmes > Vêtements > Robes > Robes d'été",
  "Femmes > Vêtements > Robes > Robes d'hiver",
  'Femmes > Vêtements > Robes > Robes chics',
  'Femmes > Vêtements > Robes > Robes casual',
  'Femmes > Vêtements > Robes > Robes sans bretelles',
  'Femmes > Vêtements > Robes > Petites robes noires',
  'Femmes > Vêtements > Robes > Robes en jean',
  'Femmes > Vêtements > Robes > Autres robes',

  'Femmes > Vêtements > Jupes > Minijupes',
  'Femmes > Vêtements > Jupes > Jupes longueur genou',
  'Femmes > Vêtements > Jupes > Jupes midi',
  'Femmes > Vêtements > Jupes > Jupes longues',
  'Femmes > Vêtements > Jupes > Jupes asymétriques',

  'Femmes > Vêtements > Jupes-shorts',

  'Femmes > Vêtements > Hauts et t-shirts > Chemises',
  'Femmes > Vêtements > Hauts et t-shirts > Blouses',
  'Femmes > Vêtements > Hauts et t-shirts > Vestes',
  'Femmes > Vêtements > Hauts et t-shirts > T-shirts',
  'Femmes > Vêtements > Hauts et t-shirts > Débardeurs',
  'Femmes > Vêtements > Hauts et t-shirts > Tuniques',
  'Femmes > Vêtements > Hauts et t-shirts > Tops courts',
  'Femmes > Vêtements > Hauts et t-shirts > Blouses manches courtes',
  'Femmes > Vêtements > Hauts et t-shirts > Blouses ¾',
  'Femmes > Vêtements > Hauts et t-shirts > Blouses manches longues',
  'Femmes > Vêtements > Hauts et t-shirts > Bodies',
  'Femmes > Vêtements > Hauts et t-shirts > Tops épaules dénudées',
  'Femmes > Vêtements > Hauts et t-shirts > Cols roulés',
  'Femmes > Vêtements > Hauts et t-shirts > Tops peplum',
  'Femmes > Vêtements > Hauts et t-shirts > Tops dos nu',
  'Femmes > Vêtements > Hauts et t-shirts > Autres hauts',

  'Femmes > Vêtements > Jeans > Jeans boyfriend',
  'Femmes > Vêtements > Jeans > Jeans courts',
  'Femmes > Vêtements > Jeans > Jeans évasés',
  'Femmes > Vêtements > Jeans > Jeans taille haute',
  'Femmes > Vêtements > Jeans > Jeans troués',
  'Femmes > Vêtements > Jeans > Jeans skinny',
  'Femmes > Vêtements > Jeans > Jeans droits',
  'Femmes > Vêtements > Jeans > Autre',

  'Femmes > Vêtements > Pantalons et leggings > Pantalons courts & chinos',
  'Femmes > Vêtements > Pantalons et leggings > Pantalons à jambes larges',
  'Femmes > Vêtements > Pantalons et leggings > Pantalons skinny',
  'Femmes > Vêtements > Pantalons et leggings > Pantalons ajustés',
  'Femmes > Vêtements > Pantalons et leggings > Pantalons droits',
  'Femmes > Vêtements > Pantalons et leggings > Pantalons en cuir',
  'Femmes > Vêtements > Pantalons et leggings > Leggings',
  'Femmes > Vêtements > Pantalons et leggings > Sarouels',
  'Femmes > Vêtements > Pantalons et leggings > Autres pantalons',

  'Femmes > Vêtements > Shorts > Shorts taille basse',
  'Femmes > Vêtements > Shorts > Shorts taille haute',
  'Femmes > Vêtements > Shorts > Shorts longueur genou',
  'Femmes > Vêtements > Shorts > Short en jean',
  'Femmes > Vêtements > Shorts > Shorts en dentelle',
  'Femmes > Vêtements > Shorts > Shorts en cuir',
  'Femmes > Vêtements > Shorts > Shorts cargo',
  'Femmes > Vêtements > Shorts > Pantacourts',
  'Femmes > Vêtements > Shorts > Autres shorts',

  'Femmes > Vêtements > Combinaisons et combishorts > Combinaisons',
  'Femmes > Vêtements > Combinaisons et combishorts > Combi Shorts',
  'Femmes > Vêtements > Combinaisons et combishorts > Autres combinaisons & combishorts',

  'Femmes > Vêtements > Maillots de bain > Une pièce',
  'Femmes > Vêtements > Maillots de bain > Deux pièces',
  'Femmes > Vêtements > Maillots de bain > Paréos et sarongs',
  'Femmes > Vêtements > Maillots de bain > Autres',

  'Femmes > Vêtements > Lingerie et pyjamas > Soutiens-gorge',
  'Femmes > Vêtements > Lingerie et pyjamas > Culottes',
  'Femmes > Vêtements > Lingerie et pyjamas > Ensembles',
  'Femmes > Vêtements > Lingerie et pyjamas > Gaines',
  'Femmes > Vêtements > Lingerie et pyjamas > Pyjamas et tenues de nuit',
  'Femmes > Vêtements > Lingerie et pyjamas > Peignoirs',
  'Femmes > Vêtements > Lingerie et pyjamas > Collants',
  'Femmes > Vêtements > Lingerie et pyjamas > Chaussettes',
  'Femmes > Vêtements > Lingerie et pyjamas > Accessoires de lingerie',
  'Femmes > Vêtements > Lingerie et pyjamas > Autres',

  'Femmes > Vêtements > Maternité > Tops maternité',
  'Femmes > Vêtements > Maternité > Robes maternité',
  'Femmes > Vêtements > Maternité > Jupes maternité',
  'Femmes > Vêtements > Maternité > Pantalons maternité',
  'Femmes > Vêtements > Maternité > Shorts maternité',
  'Femmes > Vêtements > Maternité > Combinaisons & combi shorts maternité',
  'Femmes > Vêtements > Maternité > Pulls à capuche & pulls maternité',
  'Femmes > Vêtements > Maternité > Manteaux & vestes maternité',
  'Femmes > Vêtements > Maternité > Maillots & tenues de plage maternité',
  'Femmes > Vêtements > Maternité > Sous-vêtements maternité > Sous-vêtements maternité',
  'Femmes > Vêtements > Maternité > Sous-vêtements maternité > Tenues de nuit maternité',
  'Femmes > Vêtements > Maternité > Sous-vêtements maternité > Soutiens-gorge grossesse & allaitement',
  'Femmes > Vêtements > Maternité > Vêtements de sport',
  "Femmes > Vêtements > Vêtements de sport > Vêtements d'extérieur",
  'Femmes > Vêtements > Vêtements de sport > Survêtements',
  'Femmes > Vêtements > Vêtements de sport > Pantalons & leggings',
  'Femmes > Vêtements > Vêtements de sport > Shorts',
  'Femmes > Vêtements > Vêtements de sport > Robes',
  'Femmes > Vêtements > Vêtements de sport > Jupes',
  'Femmes > Vêtements > Vêtements de sport > Hauts & t-shirts',
  'Femmes > Vêtements > Vêtements de sport > Maillots',
  'Femmes > Vêtements > Vêtements de sport > Sweats et sweats à capuche',
  'Femmes > Vêtements > Vêtements de sport > Accessoires de sports > Lunettes',
  'Femmes > Vêtements > Vêtements de sport > Accessoires de sports > Gants',
  'Femmes > Vêtements > Vêtements de sport > Accessoires de sports > Chapeaux',
  'Femmes > Vêtements > Vêtements de sport > Accessoires de sports > Écharpes',
  'Femmes > Vêtements > Vêtements de sport > Accessoires de sports > Bracelets',
  'Femmes > Vêtements > Vêtements de sport > Brassières',
  'Femmes > Vêtements > Vêtements de sport > Autres',
  'Femmes > Vêtements > Costumes et tenues particulières',
  'Femmes > Vêtements > Autres',

  // ── FEMMES > CHAUSSURES ─────────────────────────────────────────────────
  'Femmes > Chaussures > Ballerines',
  'Femmes > Chaussures > Mocassins et chaussures bateau',
  'Femmes > Chaussures > Bottes > Bottines',
  'Femmes > Chaussures > Bottes > Bottes mi-hautes',
  'Femmes > Chaussures > Bottes > Bottes hautes',
  'Femmes > Chaussures > Bottes > Cuissardes',
  'Femmes > Chaussures > Bottes > Bottes de neige',
  'Femmes > Chaussures > Bottes > Bottes de pluie',
  'Femmes > Chaussures > Bottes > Bottes de travail',
  'Femmes > Chaussures > Mules et sabots',
  'Femmes > Chaussures > Espadrilles',
  'Femmes > Chaussures > Claquettes et tongs',
  'Femmes > Chaussures > Chaussures à talons',
  'Femmes > Chaussures > Chaussures à lacets',
  'Femmes > Chaussures > Babies et Mary-Jane',
  'Femmes > Chaussures > Sandales',
  'Femmes > Chaussures > Chaussons et pantoufles',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de basket',
  "Femmes > Chaussures > Chaussures de sport > Chaussures d'escalade",
  'Femmes > Chaussures > Chaussures de sport > Chaussures de cyclisme',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de danse',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de foot',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de golf',
  'Femmes > Chaussures > Chaussures de sport > Chaussures et bottes de randonnée',
  'Femmes > Chaussures > Chaussures de sport > Patins à glace',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de foot en salle',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de fitness',
  'Femmes > Chaussures > Chaussures de sport > Bottes de moto',
  'Femmes > Chaussures > Chaussures de sport > Patins à roulettes et rollers',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de course',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de ski',
  'Femmes > Chaussures > Chaussures de sport > Bottes de snowboard',
  'Femmes > Chaussures > Chaussures de sport > Chaussures aquatiques',
  'Femmes > Chaussures > Chaussures de sport > Chaussures de tennis',
  'Femmes > Chaussures > Baskets',

  // ── FEMMES > SACS ───────────────────────────────────────────────────────
  'Femmes > Sacs > Sacs à dos',
  'Femmes > Sacs > Sacs de plage',
  'Femmes > Sacs > Mallettes',
  'Femmes > Sacs > Sacs seau',
  'Femmes > Sacs > Sacs banane',
  'Femmes > Sacs > Pochettes',
  'Femmes > Sacs > Housses pour vêtements',
  'Femmes > Sacs > Sacs de sport',
  'Femmes > Sacs > Sacs à main',
  'Femmes > Sacs > Besaces',
  'Femmes > Sacs > Fourre-tout et sacs marins',
  'Femmes > Sacs > Sacs de voyage',
  'Femmes > Sacs > Trousses à maquillage',
  'Femmes > Sacs > Cartables et sacoches',
  'Femmes > Sacs > Sacs à bandoulière',
  'Femmes > Sacs > Sacs fourre-tout',
  'Femmes > Sacs > Porte-monnaie',
  'Femmes > Sacs > Wristlets',

  // ── FEMMES > ACCESSOIRES ────────────────────────────────────────────────
  'Femmes > Accessoires > Bandanas et foulards pour cheveux',
  'Femmes > Accessoires > Ceintures',
  'Femmes > Accessoires > Gants',
  'Femmes > Accessoires > Accessoires pour cheveux',
  'Femmes > Accessoires > Mouchoirs de poche',
  'Femmes > Accessoires > Chapeaux & casquettes > Cagoules',
  'Femmes > Accessoires > Chapeaux & casquettes > Bonnets',
  'Femmes > Accessoires > Chapeaux & casquettes > Casquettes',
  'Femmes > Accessoires > Chapeaux & casquettes > Cache-oreilles',
  'Femmes > Accessoires > Chapeaux & casquettes > Fascinators',
  'Femmes > Accessoires > Chapeaux & casquettes > Chapeaux',
  'Femmes > Accessoires > Chapeaux & casquettes > Bandeaux',
  'Femmes > Accessoires > Bijoux > Bracelets de cheville',
  'Femmes > Accessoires > Bijoux > Bijoux de corps',
  'Femmes > Accessoires > Bijoux > Bracelets',
  'Femmes > Accessoires > Bijoux > Broches',
  'Femmes > Accessoires > Bijoux > Breloques et pendentifs',
  "Femmes > Accessoires > Bijoux > Boucles d'oreilles",
  'Femmes > Accessoires > Bijoux > Ensembles de bijoux',
  'Femmes > Accessoires > Bijoux > Colliers',
  'Femmes > Accessoires > Bijoux > Bagues',
  'Femmes > Accessoires > Bijoux > Autres bijoux',
  'Femmes > Accessoires > Porte-clés',
  'Femmes > Accessoires > Écharpes et châles',
  'Femmes > Accessoires > Lunettes de soleil',
  'Femmes > Accessoires > Parapluies',
  'Femmes > Accessoires > Montres',
  'Femmes > Accessoires > Autres accessoires',

  // ── FEMMES > BEAUTÉ ─────────────────────────────────────────────────────
  'Femmes > Beauté > Maquillage',
  'Femmes > Beauté > Parfums',
  'Femmes > Beauté > Soins du visage',
  'Femmes > Beauté > Accessoires de beauté',
  'Femmes > Beauté > Soin mains',
  'Femmes > Beauté > Manucure',
  'Femmes > Beauté > Soins du corps',
  'Femmes > Beauté > Soins cheveux',
  'Femmes > Beauté > Autres cosmétiques et accessoires',

  // ── HOMMES > VÊTEMENTS ──────────────────────────────────────────────────
  'Hommes > Vêtements > Jeans > Jeans troués',
  'Hommes > Vêtements > Jeans > Jeans skinny',
  'Hommes > Vêtements > Jeans > Jeans slim',
  'Hommes > Vêtements > Jeans > Jeans coupe droite',

  'Hommes > Vêtements > Manteaux et vestes > Manteaux > Duffle-coats',
  'Hommes > Vêtements > Manteaux et vestes > Manteaux > Pardessus et manteaux longs',
  'Hommes > Vêtements > Manteaux et vestes > Manteaux > Parkas',
  'Hommes > Vêtements > Manteaux et vestes > Manteaux > Cabans',
  'Hommes > Vêtements > Manteaux et vestes > Manteaux > Imperméables',
  'Hommes > Vêtements > Manteaux et vestes > Manteaux > Trenchs',
  'Hommes > Vêtements > Manteaux et vestes > Vestes sans manches',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Perfectos et blousons de moto',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Blousons aviateur',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes en jean',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes militaires et utilitaires',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes polaires',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes Harrington',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Doudounes',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes matelassées',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes chemises',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes de ski et snowboard',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Blousons teddy',
  'Hommes > Vêtements > Manteaux et vestes > Vestes > Vestes coupe-vent',
  'Hommes > Vêtements > Manteaux et vestes > Ponchos',

  'Hommes > Vêtements > Hauts et t-shirts > Chemises',
  'Hommes > Vêtements > Hauts et t-shirts > T-shirts',
  'Hommes > Vêtements > Hauts et t-shirts > Polos',
  'Hommes > Vêtements > Hauts et t-shirts > T-shirts sans manches',

  'Hommes > Vêtements > Costumes et blazers > Blazers',
  'Hommes > Vêtements > Costumes et blazers > Pantalons de costume',
  'Hommes > Vêtements > Costumes et blazers > Gilets de costume',
  'Hommes > Vêtements > Costumes et blazers > Ensembles costume',
  'Hommes > Vêtements > Costumes et blazers > Costumes de mariage',
  'Hommes > Vêtements > Costumes et blazers > Autres',

  'Hommes > Vêtements > Sweats et pulls > Sweats',
  'Hommes > Vêtements > Sweats et pulls > Pulls et pulls à capuche',
  'Hommes > Vêtements > Sweats et pulls > Pulls à capuche avec zip',
  'Hommes > Vêtements > Sweats et pulls > Cardigans',
  'Hommes > Vêtements > Sweats et pulls > Pulls ras de cou',
  'Hommes > Vêtements > Sweats et pulls > Sweats à col V',
  'Hommes > Vêtements > Sweats et pulls > Pulls à col roulé',
  'Hommes > Vêtements > Sweats et pulls > Sweats longs',
  "Hommes > Vêtements > Sweats et pulls > Pulls d'hiver",
  'Hommes > Vêtements > Sweats et pulls > Vestes',
  'Hommes > Vêtements > Sweats et pulls > Autres',

  'Hommes > Vêtements > Pantalons > Chinos',
  'Hommes > Vêtements > Pantalons > Jogging',
  'Hommes > Vêtements > Pantalons > Pantalons skinny',
  'Hommes > Vêtements > Pantalons > Pantacourts',
  'Hommes > Vêtements > Pantalons > Pantalons de costume',
  'Hommes > Vêtements > Pantalons > Pantalons à jambes larges',
  'Hommes > Vêtements > Pantalons > Autres pantalons',

  'Hommes > Vêtements > Shorts > Shorts cargo',
  'Hommes > Vêtements > Shorts > Shorts chino',
  'Hommes > Vêtements > Shorts > Shorts en jean',
  'Hommes > Vêtements > Shorts > Autres shorts',

  'Hommes > Vêtements > Sous-vêtements et chaussettes > Sous-vêtements',
  'Hommes > Vêtements > Sous-vêtements et chaussettes > Chaussettes',
  'Hommes > Vêtements > Sous-vêtements et chaussettes > Peignoirs',
  'Hommes > Vêtements > Sous-vêtements et chaussettes > Autres',
  'Hommes > Vêtements > Pyjamas > Pyjamas une-pièce',
  'Hommes > Vêtements > Pyjamas > Bas de pyjama',
  'Hommes > Vêtements > Pyjamas > Ensembles de pyjamas',
  'Hommes > Vêtements > Pyjamas > Hauts de pyjama',
  'Hommes > Vêtements > Maillots de bain',
  "Hommes > Vêtements > Vêtements de sport et accessoires > Vêtements d'extérieur",
  'Hommes > Vêtements > Vêtements de sport et accessoires > Survêtements',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Pantalons',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Shorts',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Hauts et t-shirts',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Maillots',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Pulls & sweats',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Accessoires de sports > Lunettes',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Accessoires de sports > Gants',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Accessoires de sports > Chapeaux et casquettes',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Accessoires de sports > Écharpes',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Accessoires de sports > Bracelets',
  'Hommes > Vêtements > Vêtements de sport et accessoires > Autres',
  'Hommes > Vêtements > Vêtements spécialisés et costumes',
  'Hommes > Vêtements > Autres',

  // ── HOMMES > CHAUSSURES ─────────────────────────────────────────────────
  'Hommes > Chaussures > Mocassins et chaussures bateau',
  'Hommes > Chaussures > Bottes > Bottines Chelsea et sans lacets',
  "Hommes > Chaussures > Bottes > Bottines à lacets",
  'Hommes > Chaussures > Bottes > Bottes de neige',
  'Hommes > Chaussures > Bottes > Bottes de pluie',
  'Hommes > Chaussures > Bottes > Bottes de travail',
  'Hommes > Chaussures > Mules et sabots',
  'Hommes > Chaussures > Espadrilles',
  'Hommes > Chaussures > Claquettes et tongs',
  'Hommes > Chaussures > Chaussures habillées',
  'Hommes > Chaussures > Sandales',
  'Hommes > Chaussures > Chaussons et pantoufles',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de basket',
  "Hommes > Chaussures > Chaussures de sport > Chaussures d'escalade",
  'Hommes > Chaussures > Chaussures de sport > Chaussures de cyclisme',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de danse',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de foot',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de golf',
  'Hommes > Chaussures > Chaussures de sport > Chaussures et bottes de randonnée',
  'Hommes > Chaussures > Chaussures de sport > Patins à glace',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de foot en salle',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de fitness',
  'Hommes > Chaussures > Chaussures de sport > Bottes de moto',
  'Hommes > Chaussures > Chaussures de sport > Patins à roulettes et rollers',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de course',
  'Hommes > Chaussures > Chaussures de sport > Bottes de ski',
  'Hommes > Chaussures > Chaussures de sport > Bottes de snowboard',
  'Hommes > Chaussures > Chaussures de sport > Chaussures aquatiques',
  'Hommes > Chaussures > Chaussures de sport > Chaussures de tennis',
  'Hommes > Chaussures > Baskets',

  // ── HOMMES > ACCESSOIRES ────────────────────────────────────────────────
  'Hommes > Accessoires > Sacs et sacoches > Sacs à dos',
  'Hommes > Accessoires > Sacs et sacoches > Mallettes',
  'Hommes > Accessoires > Sacs et sacoches > Sacs banane',
  'Hommes > Accessoires > Sacs et sacoches > Housses pour vêtements',
  'Hommes > Accessoires > Sacs et sacoches > Sacs de sport',
  'Hommes > Accessoires > Sacs et sacoches > Fourre-tout et sacs marins',
  'Hommes > Accessoires > Sacs et sacoches > Bagages et valises',
  'Hommes > Accessoires > Sacs et sacoches > Cartables et sacoches',
  'Hommes > Accessoires > Sacs et sacoches > Sacs à bandoulière',
  'Hommes > Accessoires > Sacs et sacoches > Porte-monnaie',
  'Hommes > Accessoires > Bandanas et foulards pour cheveux',
  'Hommes > Accessoires > Ceintures',
  'Hommes > Accessoires > Bretelles',
  'Hommes > Accessoires > Gants',
  'Hommes > Accessoires > Mouchoirs de poche',
  'Hommes > Accessoires > Chapeaux et casquettes > Cagoules',
  'Hommes > Accessoires > Chapeaux et casquettes > Bonnets',
  'Hommes > Accessoires > Chapeaux et casquettes > Casquettes',
  'Hommes > Accessoires > Chapeaux et casquettes > Chapeaux',
  'Hommes > Accessoires > Bijoux > Bracelets',
  'Hommes > Accessoires > Bijoux > Breloques et pendentifs',
  'Hommes > Accessoires > Bijoux > Boutons de manchette',
  "Hommes > Accessoires > Bijoux > Boucles d'oreilles",
  'Hommes > Accessoires > Bijoux > Colliers',
  'Hommes > Accessoires > Bijoux > Bagues',
  'Hommes > Accessoires > Bijoux > Autre',
  'Hommes > Accessoires > Pochettes de costume',
  'Hommes > Accessoires > Écharpes et châles',
  'Hommes > Accessoires > Lunettes de soleil',
  'Hommes > Accessoires > Cravates et nœuds papillons',
  'Hommes > Accessoires > Montres',
  'Hommes > Accessoires > Autres',

  // ── HOMMES > SOINS ──────────────────────────────────────────────────────
  'Hommes > Soins > Soins visage',
  'Hommes > Soins > Accessoires',
  'Hommes > Soins > Soins cheveux',
  'Hommes > Soins > Soins du corps',
  'Hommes > Soins > Soins mains et ongles',
  'Hommes > Soins > Parfums',
  'Hommes > Soins > Maquillage',
  'Hommes > Soins > Coffrets',
  'Hommes > Soins > Autres cosmétiques',

  // ── ENFANTS > VÊTEMENTS POUR FILLES ────────────────────────────────────
  'Enfants > Vêtements pour filles > Bébé filles',
  'Enfants > Vêtements pour filles > Chaussures',
  "Enfants > Vêtements pour filles > Vêtements d'extérieur",
  'Enfants > Vêtements pour filles > Pulls & sweats',
  'Enfants > Vêtements pour filles > Chemises et t-shirts',
  'Enfants > Vêtements pour filles > Robes',
  'Enfants > Vêtements pour filles > Jupes',
  'Enfants > Vêtements pour filles > Pantalons et shorts',
  'Enfants > Vêtements pour filles > Sacs et sacs à dos',
  'Enfants > Vêtements pour filles > Accessoires',
  'Enfants > Vêtements pour filles > Équipements de natation',
  'Enfants > Vêtements pour filles > Sous-vêtements',
  'Enfants > Vêtements pour filles > Pyjamas et chemises de nuit',
  'Enfants > Vêtements pour filles > Vêtements de sport',
  'Enfants > Vêtements pour filles > Lots de vêtements',
  'Enfants > Vêtements pour filles > Jumeaux et plus',
  'Enfants > Vêtements pour filles > Déguisements',
  'Enfants > Vêtements pour filles > Tenues de soirée',
  'Enfants > Vêtements pour filles > Autres',

  // ── ENFANTS > VÊTEMENTS POUR GARÇONS ───────────────────────────────────
  'Enfants > Vêtements pour garçons > Bébé garçons',
  'Enfants > Vêtements pour garçons > Chaussures',
  "Enfants > Vêtements pour garçons > Vêtements d'extérieur",
  'Enfants > Vêtements pour garçons > Pulls & sweats',
  'Enfants > Vêtements pour garçons > Chemises et t-shirts',
  'Enfants > Vêtements pour garçons > Pantalons et shorts',
  'Enfants > Vêtements pour garçons > Sacs et sacs à dos',
  'Enfants > Vêtements pour garçons > Accessoires',
  'Enfants > Vêtements pour garçons > Équipements de natation',
  'Enfants > Vêtements pour garçons > Sous-vêtements',
  'Enfants > Vêtements pour garçons > Pyjamas',
  'Enfants > Vêtements pour garçons > Vêtements de sport',
  'Enfants > Vêtements pour garçons > Lots de vêtements',
  'Enfants > Vêtements pour garçons > Jumeaux et plus',
  'Enfants > Vêtements pour garçons > Déguisements',
  'Enfants > Vêtements pour garçons > Tenues de soirée',
  'Enfants > Vêtements pour garçons > Autres',

  // ── ENFANTS > JEUX ET JOUETS ────────────────────────────────────────────
  'Enfants > Jeux et jouets > Figurines et accessoires',
  'Enfants > Jeux et jouets > Loisirs créatifs',
  'Enfants > Jeux et jouets > Activités et jouets pour bébé',
  'Enfants > Jeux et jouets > Jeux de construction',
  'Enfants > Jeux et jouets > Poupées poupons et accessoires',
  'Enfants > Jeux et jouets > Déguisements et jeux de rôle',
  'Enfants > Jeux et jouets > Jeux éducatifs',
  'Enfants > Jeux et jouets > Jeux et jouets électroniques',
  'Enfants > Jeux et jouets > Jeux/jouets musicaux et instruments',
  'Enfants > Jeux et jouets > Jeux de cirque fidgets et gadgets',
  'Enfants > Jeux et jouets > Jeux de sport et de plein air',
  'Enfants > Jeux et jouets > Peluches',
  'Enfants > Jeux et jouets > Voitures trains et autres véhicules',

  // ── ENFANTS > POUSSETTES, PORTE-BÉBÉ ET SIÈGES AUTO ───────────────────
  'Enfants > Poussettes porte-bébé et sièges auto > Porte-bébé et écharpes',
  'Enfants > Poussettes porte-bébé et sièges auto > Poussettes et landaus',
  'Enfants > Poussettes porte-bébé et sièges auto > Accessoires de poussette',
  'Enfants > Poussettes porte-bébé et sièges auto > Sièges auto',
  'Enfants > Poussettes porte-bébé et sièges auto > Rehausseurs',
  'Enfants > Poussettes porte-bébé et sièges auto > Accessoires pour siège auto',

  // ── MAISON > PETITS APPAREILS DE CUISINE ────────────────────────────────
  'Maison > Petits appareils de cuisine > Bouilloires',
  "Maison > Petits appareils de cuisine > Préparation du café du thé et de l'expresso",
  'Maison > Petits appareils de cuisine > Grille-pain',
  'Maison > Petits appareils de cuisine > Blenders mixeurs et robots de cuisine',
  'Maison > Petits appareils de cuisine > Micro-ondes',
  'Maison > Petits appareils de cuisine > Friteuses',
  'Maison > Petits appareils de cuisine > Plaques de cuisson',
  'Maison > Petits appareils de cuisine > Grils et planchas',
  'Maison > Petits appareils de cuisine > Extracteurs de jus',
  "Maison > Petits appareils de cuisine > Distributeurs d'eau et de boissons",
  'Maison > Petits appareils de cuisine > Appareils spécialisés',
  'Maison > Petits appareils de cuisine > Accessoires pour petits appareils de cuisine',
  'Maison > Petits appareils de cuisine > Pièces détachées pour petits appareils de cuisine',

  // ── MAISON > CUISSON ET PÂTISSERIE ─────────────────────────────────────
  'Maison > Cuisson et pâtisserie > Casseroles',
  'Maison > Cuisson et pâtisserie > Poêles',
  'Maison > Cuisson et pâtisserie > Plaques pour la cuisson',
  'Maison > Cuisson et pâtisserie > Plats pour le four',
  'Maison > Cuisson et pâtisserie > Moules de cuisson',
  'Maison > Cuisson et pâtisserie > Matériel de cuisson et de pâtisserie spécialisé',
  'Maison > Cuisson et pâtisserie > Batteries de cuisine',
  'Maison > Cuisson et pâtisserie > Accessoires pour la cuisine et la pâtisserie',

  // ── MAISON > OUTILS DE CUISINE ──────────────────────────────────────────
  'Maison > Outils de cuisine > Planches à découper',
  'Maison > Outils de cuisine > Ustensiles de cuisine',
  'Maison > Outils de cuisine > Balances de cuisine',
  'Maison > Outils de cuisine > Tasses et cuillères à mesurer',
  'Maison > Outils de cuisine > Thermomètres alimentaires',
  'Maison > Outils de cuisine > Bols à mélanger',
  'Maison > Outils de cuisine > Passoires tamis et chinois',
  'Maison > Outils de cuisine > Stockage alimentaire',
  'Maison > Outils de cuisine > Accessoires de bar',
  'Maison > Outils de cuisine > Ustensiles de cuisine spécialisés',

  // ── MAISON > ARTS DE LA TABLE ───────────────────────────────────────────
  'Maison > Arts de la table > Couverts',
  'Maison > Arts de la table > Vaisselle',
  'Maison > Arts de la table > Verres',
  'Maison > Arts de la table > Vaisselle de service',

  // ── MAISON > ENTRETIEN DE LA MAISON ────────────────────────────────────
  'Maison > Entretien de la maison > Chauffage climatisation et ventilation',
  "Maison > Entretien de la maison > Fers à repasser et entretien du linge",
  'Maison > Entretien de la maison > Aspirateurs et nettoyage',

  // ── MAISON > TEXTILES ───────────────────────────────────────────────────
  'Maison > Textiles > Linge de lit',
  'Maison > Textiles > Couvertures',
  'Maison > Textiles > Rideaux et stores',
  'Maison > Textiles > Coussins décoratifs',
  'Maison > Textiles > Housses',
  'Maison > Textiles > Tapis',
  'Maison > Textiles > Linge de table',
  'Maison > Textiles > Tapisseries',
  'Maison > Textiles > Serviettes',

  // ── MAISON > DÉCORATION ─────────────────────────────────────────────────
  "Maison > Décoration > Bougies et parfums d'ambiance",
  'Maison > Décoration > Horloges',
  'Maison > Décoration > Sculptures et figurines',
  'Maison > Décoration > Accessoires décoratifs',
  'Maison > Décoration > Plantes et fleurs artificielles',
  'Maison > Décoration > Accessoires pour cheminées',
  'Maison > Décoration > Éclairage',
  'Maison > Décoration > Étagères murales',
  'Maison > Décoration > Encadrements',
  'Maison > Décoration > Miroirs',
  'Maison > Décoration > Rangement et organisation',
  'Maison > Décoration > Vases',
  'Maison > Décoration > Décorations murales',

  // ── MAISON > FOURNITURES DE BUREAU ─────────────────────────────────────
  'Maison > Fournitures de bureau > Agendas et organiseurs',
  'Maison > Fournitures de bureau > Carnets et blocs-notes',
  'Maison > Fournitures de bureau > Trousses',
  'Maison > Fournitures de bureau > Marque-pages',
  'Maison > Fournitures de bureau > Calculatrices',
  'Maison > Fournitures de bureau > Accessoires de bureau',
  'Maison > Fournitures de bureau > Organiseurs de documents',
  "Maison > Fournitures de bureau > Fournitures d'écriture",
  'Maison > Fournitures de bureau > Outils de dessin technique',
  'Maison > Fournitures de bureau > Rubans adhésifs pinces et attaches',
  'Maison > Fournitures de bureau > Agrafeuses et perforatrices',
  'Maison > Fournitures de bureau > Matériel de présentation',
  'Maison > Fournitures de bureau > Matériel électronique de bureau',
  'Maison > Fournitures de bureau > Coffres-forts',

  // ── MAISON > CÉLÉBRATIONS ET FÊTES ─────────────────────────────────────
  'Maison > Célébrations et fêtes > Banderoles drapeaux et guirlandes',
  'Maison > Célébrations et fêtes > Cartes et enveloppes',
  'Maison > Célébrations et fêtes > Papier cadeau et sacs',
  'Maison > Célébrations et fêtes > Décorations saisonnières',
  'Maison > Célébrations et fêtes > Accessoires de fête',
  'Maison > Célébrations et fêtes > Décorations de table',
  'Maison > Célébrations et fêtes > Décorations pour le sapin',
  'Maison > Célébrations et fêtes > Couronnes',

  // ── MAISON > OUTILS ET BRICOLAGE ───────────────────────────────────────
  'Maison > Outils et bricolage > Outils électriques',
  'Maison > Outils et bricolage > Outils à main',
  'Maison > Outils et bricolage > Outils de mesure',
  'Maison > Outils et bricolage > Outils et accessoires de peinture',
  'Maison > Outils et bricolage > Outils de plomberie',
  "Maison > Outils et bricolage > Outils d'électricien",
  'Maison > Outils et bricolage > Outils de maçonnerie',
  'Maison > Outils et bricolage > Accessoires pour outils',
  'Maison > Outils et bricolage > Équipement de protection',
  'Maison > Outils et bricolage > Transport et rangement des outils',
  "Maison > Outils et bricolage > Équipement d'atelier et de chantier",
  'Maison > Outils et bricolage > Quincaillerie',
  'Maison > Outils et bricolage > Maisons connectées et sécurité',

  // ── MAISON > EXTÉRIEUR ET JARDIN ───────────────────────────────────────
  "Maison > Extérieur et jardin > Outils électriques d'extérieur",
  "Maison > Extérieur et jardin > Accessoires pour outils électriques d'extérieur",
  'Maison > Extérieur et jardin > Outils manuels de jardin',
  'Maison > Extérieur et jardin > Pots jardinières et accessoires',
  "Maison > Extérieur et jardin > Équipement d'arrosage",
  "Maison > Extérieur et jardin > Décorations de jardin et d'extérieur",
  'Maison > Extérieur et jardin > Cuisine et grillade d\'extérieur',
  'Maison > Extérieur et jardin > Spas piscines et équipements',
  'Maison > Extérieur et jardin > Instruments météorologiques',
  'Maison > Extérieur et jardin > Outils de déneigement',

  // ── MAISON > ANIMAUX ────────────────────────────────────────────────────
  'Maison > Animaux > Chiens',
  'Maison > Animaux > Chats',
  'Maison > Animaux > Rongeurs & co',
  'Maison > Animaux > Poissons',
  'Maison > Animaux > Oiseaux',
  'Maison > Animaux > Reptiles',

  // ── ÉLECTRONIQUE > JEUX VIDÉO ET CONSOLES ──────────────────────────────
  'Électronique > Jeux vidéo et consoles > Consoles',
  'Électronique > Jeux vidéo et consoles > Jeux',
  'Électronique > Jeux vidéo et consoles > Manettes',
  'Électronique > Jeux vidéo et consoles > Casques gaming',
  'Électronique > Jeux vidéo et consoles > Simulateurs',
  'Électronique > Jeux vidéo et consoles > Réalité virtuelle',
  'Électronique > Jeux vidéo et consoles > Accessoires',

  // ── ÉLECTRONIQUE > ORDINATEURS ET ACCESSOIRES ──────────────────────────
  'Électronique > Ordinateurs et accessoires > Ordinateurs portables',
  'Électronique > Ordinateurs et accessoires > Ordinateurs de bureau',
  'Électronique > Ordinateurs et accessoires > Pièces détachées et composants informatiques',
  'Électronique > Ordinateurs et accessoires > Supports vierges',
  'Électronique > Ordinateurs et accessoires > Accessoires informatiques',
  'Électronique > Ordinateurs et accessoires > Accessoires pour ordinateurs portables',
  'Électronique > Ordinateurs et accessoires > Stations d\'accueil et concentrateurs USB',
  'Électronique > Ordinateurs et accessoires > Claviers et accessoires',
  'Électronique > Ordinateurs et accessoires > Souris',
  'Électronique > Ordinateurs et accessoires > Tapis de souris',
  'Électronique > Ordinateurs et accessoires > Moniteurs et accessoires',
  'Électronique > Ordinateurs et accessoires > Haut-parleurs pour ordinateurs',
  "Électronique > Ordinateurs et accessoires > Microphones d'ordinateur",
  'Électronique > Ordinateurs et accessoires > Webcams',
  'Électronique > Ordinateurs et accessoires > Équipements réseau',
  'Électronique > Ordinateurs et accessoires > Imprimantes et accessoires',
  'Électronique > Ordinateurs et accessoires > Scanners et accessoires',
  'Électronique > Ordinateurs et accessoires > Tablettes tactiles et tablettes à stylets',

  // ── ÉLECTRONIQUE > TÉLÉPHONES PORTABLES ────────────────────────────────
  'Électronique > Téléphones portables et équipements de communication > Téléphones portables',
  'Électronique > Téléphones portables et équipements de communication > Pièces de rechange et accessoires pour téléphones portables',
  'Électronique > Téléphones portables et équipements de communication > Téléphones fixes',
  'Électronique > Téléphones portables et équipements de communication > Fax',
  'Électronique > Téléphones portables et équipements de communication > Communication radio',
  'Électronique > Téléphones portables et équipements de communication > Téléphones portables factices',

  // ── ÉLECTRONIQUE > AUDIO ────────────────────────────────────────────────
  'Électronique > Audio casques et hi-fi > Casques audio et écouteurs',
  'Électronique > Audio casques et hi-fi > Lecteurs de musique portables',
  'Électronique > Audio casques et hi-fi > Radios portables',
  'Électronique > Audio casques et hi-fi > Enceintes portables',
  'Électronique > Audio casques et hi-fi > Enceintes connectées',
  'Électronique > Audio casques et hi-fi > Systèmes audio domestiques',
  'Électronique > Audio casques et hi-fi > Accessoires pour appareils audio',
  'Électronique > Audio casques et hi-fi > Pièces de rechange pour appareils hi-fi et audio domestiques',

  // ── ÉLECTRONIQUE > APPAREILS PHOTO ─────────────────────────────────────
  'Électronique > Appareils photo et accessoires > Appareils photo',
  'Électronique > Appareils photo et accessoires > Objectifs',
  'Électronique > Appareils photo et accessoires > Flashs',
  'Électronique > Appareils photo et accessoires > Cartes mémoire',
  'Électronique > Appareils photo et accessoires > Trépieds et monopodes',
  'Électronique > Appareils photo et accessoires > Stabilisateurs et supports',
  'Électronique > Appareils photo et accessoires > Équipements pour chambres noires',
  'Électronique > Appareils photo et accessoires > Équipement pour studio',
  'Électronique > Appareils photo et accessoires > Drones et accessoires',
  'Électronique > Appareils photo et accessoires > Accessoires',
  'Électronique > Appareils photo et accessoires > Pièces de rechange pour appareils photo',
  'Électronique > Appareils photo et accessoires > Autre matériel de photographie',

  // ── ÉLECTRONIQUE > TABLETTES ────────────────────────────────────────────
  'Électronique > Tablettes liseuses et accessoires > Tablettes',
  'Électronique > Tablettes liseuses et accessoires > Liseuses',
  'Électronique > Tablettes liseuses et accessoires > Blocs-notes numériques',
  'Électronique > Tablettes liseuses et accessoires > Assistants personnels',
  'Électronique > Tablettes liseuses et accessoires > Accessoires',

  // ── ÉLECTRONIQUE > TV ET HOME CINEMA ────────────────────────────────────
  'Électronique > TV et home cinema > Téléviseurs',
  'Électronique > TV et home cinema > Projecteurs',
  'Électronique > TV et home cinema > Passerelles multimédias',
  'Électronique > TV et home cinema > Antennes de télévision',
  'Électronique > TV et home cinema > Antennes paraboliques',
  'Électronique > TV et home cinema > Décodeurs vidéo',
  'Électronique > TV et home cinema > Récepteurs de télévision',
  'Électronique > TV et home cinema > Systèmes de home cinema',
  'Électronique > TV et home cinema > Lecteurs Blu-ray',
  'Électronique > TV et home cinema > Lecteurs DVD',
  'Électronique > TV et home cinema > Magnétoscopes',
  'Électronique > TV et home cinema > Autres appareils de lecture vidéo',
  'Électronique > TV et home cinema > Accessoires TV et home cinema',

  // ── ÉLECTRONIQUE > PRODUITS DE BEAUTÉ ──────────────────────────────────
  'Électronique > Produits de beauté et de soins personnels > Appareils de coiffure',
  'Électronique > Produits de beauté et de soins personnels > Appareils de beauté',
  'Électronique > Produits de beauté et de soins personnels > Rasage et épilation',
  'Électronique > Produits de beauté et de soins personnels > Appareils de massage',
  "Électronique > Produits de beauté et de soins personnels > Appareils d'hygiène bucco-dentaire",
  'Électronique > Produits de beauté et de soins personnels > Appareils de soin des ongles',
  'Électronique > Produits de beauté et de soins personnels > Pèse-personnes',

  // ── ÉLECTRONIQUE > OBJETS CONNECTÉS ────────────────────────────────────
  'Électronique > Objets connectés > Montres connectées',
  'Électronique > Objets connectés > Bracelets connectés',
  'Électronique > Objets connectés > Lunettes connectées',
  'Électronique > Objets connectés > Bagues connectées',
  'Électronique > Objets connectés > Bracelets de remplacement',
  'Électronique > Objets connectés > Coques pour montres connectées',

  // ── ÉLECTRONIQUE > AUTRES APPAREILS ────────────────────────────────────
  'Électronique > Autres appareils et accessoires > Impression et numérisation 3D',
  'Électronique > Autres appareils et accessoires > GPS et appareils de navigation par satellite',
  "Électronique > Autres appareils et accessoires > Localisateurs d'objets",
  'Électronique > Autres appareils et accessoires > Pèse-bagages',
  'Électronique > Autres appareils et accessoires > Adaptateurs',
  'Électronique > Autres appareils et accessoires > Câbles',
  'Électronique > Autres appareils et accessoires > Chargeurs',
  'Électronique > Autres appareils et accessoires > Batteries externes',
  'Électronique > Autres appareils et accessoires > Multiprises parasurtenseurs',
  'Électronique > Autres appareils et accessoires > Piles et alimentations',
  'Électronique > Autres appareils et accessoires > Autres accessoires',

  // ── DIVERTISSEMENT ──────────────────────────────────────────────────────
  'Divertissement > Livres > Fiction',
  'Divertissement > Livres > Non-fiction',
  'Divertissement > Livres > Enfants et jeunes adultes',
  'Divertissement > Livres > Bandes dessinées mangas et romans graphiques',
  'Divertissement > Livres > Manuels scolaires et ressources pédagogiques',
  "Divertissement > Livres > Livres de coloriage et d'activités et revues de jeux",

  'Divertissement > Musique > Cassettes audio',
  'Divertissement > Musique > CD',
  'Divertissement > Musique > MiniDiscs',
  'Divertissement > Musique > Vinyles',

  'Divertissement > Vidéo > Blu-ray 4K',
  'Divertissement > Vidéo > Betamax',
  'Divertissement > Vidéo > Blu-ray',
  'Divertissement > Vidéo > DVD',
  'Divertissement > Vidéo > HD DVD',
  'Divertissement > Vidéo > LaserDisc',
  'Divertissement > Vidéo > VHS',

  // ── LOISIRS ET COLLECTIONS ──────────────────────────────────────────────
  'Loisirs et collections > Cartes à collectionner > Cartes à collectionner à l\'unité',
  'Loisirs et collections > Cartes à collectionner > Boosters',
  'Loisirs et collections > Cartes à collectionner > Coffrets de boosters',
  'Loisirs et collections > Cartes à collectionner > Jeux de cartes',
  'Loisirs et collections > Cartes à collectionner > Lots de cartes à collectionner',
  'Loisirs et collections > Cartes à collectionner > Cartes non découpées',

  'Loisirs et collections > Souvenirs > Souvenirs de sport',
  'Loisirs et collections > Souvenirs > Souvenirs de musique',
  'Loisirs et collections > Souvenirs > Souvenirs TV et cinéma',
  'Loisirs et collections > Souvenirs > Autres souvenirs',

  'Loisirs et collections > Pièces de monnaie et billets > Billets',
  'Loisirs et collections > Pièces de monnaie et billets > Pièces de monnaie',
  'Loisirs et collections > Pièces de monnaie et billets > Lots',
  'Loisirs et collections > Pièces de monnaie et billets > Médailles et jetons',
  'Loisirs et collections > Pièces de monnaie et billets > Titres et actions',

  'Loisirs et collections > Timbres > Timbres à l\'unité',
  'Loisirs et collections > Timbres > Lots de timbres',
  'Loisirs et collections > Timbres > Enveloppes premier jour',
  'Loisirs et collections > Timbres > Catalogues et guides de timbres',
  'Loisirs et collections > Timbres > Outils et matériel pour timbres',

  'Loisirs et collections > Instruments de musique et équipement > Guitares et basses',
  'Loisirs et collections > Instruments de musique et équipement > Amplis et pédales',
  'Loisirs et collections > Instruments de musique et équipement > Batterie et percussions',
  'Loisirs et collections > Instruments de musique et équipement > Claviers et synthétiseurs',
  'Loisirs et collections > Instruments de musique et équipement > Instruments à cordes',
  'Loisirs et collections > Instruments de musique et équipement > Instruments à vent',
  'Loisirs et collections > Instruments de musique et équipement > Matériel de studio et sonorisation live',
  'Loisirs et collections > Instruments de musique et équipement > Équipement DJ',
  'Loisirs et collections > Instruments de musique et équipement > Équipement de karaoké',
  'Loisirs et collections > Instruments de musique et équipement > Accessoires pour la création musicale',

  'Loisirs et collections > Loisirs créatifs > Couture tricot et travaux d\'aiguille',
  'Loisirs et collections > Loisirs créatifs > Peinture',
  'Loisirs et collections > Loisirs créatifs > Dessin et esquisse',
  'Loisirs et collections > Loisirs créatifs > Calligraphie',
  'Loisirs et collections > Loisirs créatifs > Fabrication de bijoux',
  'Loisirs et collections > Loisirs créatifs > Papercraft',
  'Loisirs et collections > Loisirs créatifs > Découpe',
  'Loisirs et collections > Loisirs créatifs > Fabrication de bougies',
  'Loisirs et collections > Loisirs créatifs > Sculpture et poterie',
  'Loisirs et collections > Loisirs créatifs > Fournitures pour loisirs créatifs',
  'Loisirs et collections > Loisirs créatifs > Outils pour loisirs créatifs',

  'Loisirs et collections > Rangements pour objets de collection > Albums et classeurs',
  'Loisirs et collections > Rangements pour objets de collection > Boîtes de rangement',
  'Loisirs et collections > Rangements pour objets de collection > Protège-cartes souples',
  'Loisirs et collections > Rangements pour objets de collection > Protège-cartes rigides',
  'Loisirs et collections > Rangements pour objets de collection > Boîtes pour jeux de cartes',
  'Loisirs et collections > Rangements pour objets de collection > Intercalaires pour albums et classeurs',
  'Loisirs et collections > Rangements pour objets de collection > Recharges pour albums et classeurs',
  'Loisirs et collections > Rangements pour objets de collection > Tapis de puzzle',
  'Loisirs et collections > Rangements pour objets de collection > Autres rangements',

  'Loisirs et collections > Accessoires de jeux > Dés',
  'Loisirs et collections > Accessoires de jeux > Jetons et marqueurs de jeu',
  'Loisirs et collections > Accessoires de jeux > Tapis de jeux',
  'Loisirs et collections > Accessoires de jeux > Autres accessoires de jeux',

  // ── SPORT ───────────────────────────────────────────────────────────────
  'Sport > Cyclisme > Vélos pour enfant',
  'Sport > Cyclisme > Casques de vélo',
  'Sport > Cyclisme > Accessoires et outils pour vélo',
  'Sport > Cyclisme > Remorques pour vélo',
  'Sport > Cyclisme > Sièges enfants pour vélo',
  'Sport > Cyclisme > Pièces pour vélo',

  'Sport > Fitness course à pied et yoga > Musculation',
  'Sport > Fitness course à pied et yoga > Course à pied',
  'Sport > Fitness course à pied et yoga > Matériel de yoga et de pilates',
  'Sport > Fitness course à pied et yoga > Accessoires de fitness à domicile',
  'Sport > Fitness course à pied et yoga > Gourdes',

  "Sport > Sports de plein air > Escalade et escalade de bloc",
  'Sport > Sports de plein air > Tentes et matériel de couchage',
  'Sport > Sports de plein air > Réchauds et ustensiles de cuisine de camping',
  'Sport > Sports de plein air > Jumelles et longues-vues',
  'Sport > Sports de plein air > Glacières',
  "Sport > Sports de plein air > Systèmes et kits d'hydratation",
  'Sport > Sports de plein air > Meubles de camping',
  'Sport > Sports de plein air > Torches lampes frontales et lanternes',
  'Sport > Sports de plein air > Bâtons de randonnée',
  'Sport > Sports de plein air > Boussoles',
  'Sport > Sports de plein air > Sacs de randonnée',
  'Sport > Sports de plein air > Pêche et chasse',
  'Sport > Sports de plein air > Autres accessoires de sports de plein air',

  'Sport > Sports nautiques > Natation',
  'Sport > Sports nautiques > Bateaux gonflables',
  'Sport > Sports nautiques > Kayaks',
  'Sport > Sports nautiques > Planches de kitesurf',
  'Sport > Sports nautiques > Skimboards',
  'Sport > Sports nautiques > Paddles',
  'Sport > Sports nautiques > Bouées tractées',
  'Sport > Sports nautiques > Planches de wakeboard',
  'Sport > Sports nautiques > Skis nautiques',
  'Sport > Sports nautiques > Gilets de flottaison',
  'Sport > Sports nautiques > Casques pour sports nautiques',
  'Sport > Sports nautiques > Combinaisons gants et chaussons',
  'Sport > Sports nautiques > Accessoires pour sports nautiques',

  "Sport > Sports d'équipe > Football",
  "Sport > Sports d'équipe > Basketball",
  "Sport > Sports d'équipe > Volley-ball",
  "Sport > Sports d'équipe > Rugby",
  "Sport > Sports d'équipe > Matériel d'entraînement et d'arbitrage",
  "Sport > Sports d'équipe > Football américain",
  "Sport > Sports d'équipe > Baseball et softball",
  "Sport > Sports d'équipe > Handball",
  "Sport > Sports d'équipe > Cricket",
  "Sport > Sports d'équipe > Hockey sur gazon",
  "Sport > Sports d'équipe > Floorball",
  "Sport > Sports d'équipe > Sports gaéliques",
  "Sport > Sports d'équipe > Lacrosse",
  "Sport > Sports d'équipe > Netball",
  "Sport > Sports d'équipe > Autres équipements pour sports d'équipe",

  'Sport > Sports de raquette > Tennis',
  'Sport > Sports de raquette > Squash',
  'Sport > Sports de raquette > Badminton',
  'Sport > Sports de raquette > Racquetball',
  'Sport > Sports de raquette > Tennis de table',
  'Sport > Sports de raquette > Padel',
  'Sport > Sports de raquette > Pickleball',
  'Sport > Sports de raquette > Lunettes pour sports de raquette',

  'Sport > Golf > Accessoires de golf',
  'Sport > Golf > Sacs de golf',
  'Sport > Golf > Balles de golf',
  'Sport > Golf > Clubs de golf',
  'Sport > Golf > Gants de golf',
  'Sport > Golf > Chariots de golf',
  "Sport > Golf > Matériel d'entraînement pour le golf",

  "Sport > Équitation > Protections d'équitation",
  "Sport > Équitation > Gants d'équitation",
  "Sport > Équitation > Bombes d'équitation",
  "Sport > Équitation > Couvre-casques d'équitation",
  'Sport > Équitation > Selles et harnachement',

  'Sport > Skateboards et trottinettes > Longboards',
  'Sport > Skateboards et trottinettes > Skateboards',
  'Sport > Skateboards et trottinettes > Trottinettes',
  'Sport > Skateboards et trottinettes > Casques de skate',
  'Sport > Skateboards et trottinettes > Protections de skate',
  'Sport > Skateboards et trottinettes > Pièces et accessoires pour skating',
  'Sport > Skateboards et trottinettes > Pièces et accessoires pour skateboard',

  'Sport > Boxe et arts martiaux > Protections pour la tête',
  'Sport > Boxe et arts martiaux > Protections pour le corps',
  'Sport > Boxe et arts martiaux > Pattes d\'ours pao et boucliers',
  'Sport > Boxe et arts martiaux > Gants de boxe et d\'arts martiaux',
  'Sport > Boxe et arts martiaux > Bandes de boxe',
  "Sport > Boxe et arts martiaux > Ceintures d'arts martiaux",
  'Sport > Boxe et arts martiaux > Sacs de frappe',
  'Sport > Boxe et arts martiaux > Poires de vitesse',
  "Sport > Boxe et arts martiaux > Autres équipements pour arts martiaux",

  'Sport > Sports et jeux de loisir > Pétanque et autres jeux',
  'Sport > Sports et jeux de loisir > Matériel pour fléchettes',
  'Sport > Sports et jeux de loisir > Frisbee et disc golf',
  'Sport > Sports et jeux de loisir > Balles et ballons',
  'Sport > Sports et jeux de loisir > Billard et snooker',
  'Sport > Sports et jeux de loisir > Roundnet et spikeball',
  'Sport > Sports et jeux de loisir > Bowling',

  "Sport > Sports d'hiver > Matériel de ski",
  "Sport > Sports d'hiver > Matériel de snowboard",
  "Sport > Sports d'hiver > Hockey sur glace",
  "Sport > Sports d'hiver > Accessoires de patinage artistique",
  "Sport > Sports d'hiver > Luges",
  "Sport > Sports d'hiver > Raquettes à neige",
  "Sport > Sports d'hiver > Guêtres",
  "Sport > Sports d'hiver > Masques et lunettes de ski",
  "Sport > Sports d'hiver > Casques pour sports d'hiver",
]

/* ── Niveau 5 — sous-types connus (dérivé de NAV_PATHS, fourni aussi comme constante pour le prompt) ── */
export const VINTED_TAXONOMY_LEVEL5_FR: Record<string, string[]> = {
  'Femmes > Vêtements > Manteaux et vestes > Manteaux': ['Duffle-coats', 'Manteaux en fausse fourrure', 'Pardessus et manteaux longs', 'Parkas', 'Cabans', 'Imperméables', 'Trenchs'],
  'Femmes > Vêtements > Manteaux et vestes > Vestes': ['Perfectos et blousons de moto', 'Blousons aviateur', 'Vestes en jean', 'Vestes militaires et utilitaires', 'Vestes polaires', 'Doudounes', 'Vestes matelassées', 'Vestes chemises', 'Vestes de ski et snowboard', 'Blousons teddy', 'Vestes coupe-vent'],
  'Femmes > Vêtements > Sweats et sweats à capuche > Sweats': ['Pulls col V', 'Pulls col roulé', 'Sweats longs', "Pulls d'hiver", 'Sweats manche ¾', 'Autres sweats'],
  'Femmes > Vêtements > Vêtements de sport > Accessoires de sports': ['Lunettes', 'Gants', 'Chapeaux', 'Écharpes', 'Bracelets'],
  'Femmes > Vêtements > Maternité > Sous-vêtements maternité': ['Sous-vêtements maternité', 'Tenues de nuit maternité', 'Soutiens-gorge grossesse & allaitement'],
  'Hommes > Vêtements > Manteaux et vestes > Manteaux': ['Duffle-coats', 'Pardessus et manteaux longs', 'Parkas', 'Cabans', 'Imperméables', 'Trenchs'],
  'Hommes > Vêtements > Manteaux et vestes > Vestes': ['Perfectos et blousons de moto', 'Blousons aviateur', 'Vestes en jean', 'Vestes militaires et utilitaires', 'Vestes polaires', 'Vestes Harrington', 'Doudounes', 'Vestes matelassées', 'Vestes chemises', 'Vestes de ski et snowboard', 'Blousons teddy', 'Vestes coupe-vent'],
  'Hommes > Vêtements > Vêtements de sport et accessoires > Accessoires de sports': ['Lunettes', 'Gants', 'Chapeaux et casquettes', 'Écharpes', 'Bracelets'],
}

// Retourne tous les chemins sous forme de chaîne pour le prompt de reconnaissance
export function getNavRef(): string {
  return NAV_PATHS.join('\n')
}

// Retourne uniquement les chemins commençant par un préfixe donné
export function getNavRefFiltered(prefix: string): string {
  return NAV_PATHS.filter(p => p.startsWith(prefix)).join('\n')
}

/* ── Helpers pour dropdowns en cascade N1 > N2 > N3 > N4 > N5 ───────────── */

export function parseVintedPath(path: string): { n1: string; n2: string; n3: string; n4: string; n5: string } {
  const parts = path.split(' > ')
  return { n1: parts[0] ?? '', n2: parts[1] ?? '', n3: parts[2] ?? '', n4: parts[3] ?? '', n5: parts[4] ?? '' }
}

export function getN1List(): string[] {
  return [...new Set(NAV_PATHS.map(p => p.split(' > ')[0]))]
}

export function getN2List(n1: string): string[] {
  const prefix = n1 + ' > '
  return [...new Set(
    NAV_PATHS.filter(p => p.startsWith(prefix)).map(p => p.slice(prefix.length).split(' > ')[0]).filter(Boolean)
  )] as string[]
}

export function getN3List(n1: string, n2: string): string[] {
  const prefix = n1 + ' > ' + n2 + ' > '
  return [...new Set(
    NAV_PATHS.filter(p => p.startsWith(prefix)).map(p => p.slice(prefix.length).split(' > ')[0]).filter(Boolean)
  )] as string[]
}

export function getN4List(n1: string, n2: string, n3: string): string[] {
  const prefix = n1 + ' > ' + n2 + ' > ' + n3 + ' > '
  return [...new Set(
    NAV_PATHS.filter(p => p.startsWith(prefix)).map(p => p.slice(prefix.length).split(' > ')[0]).filter(Boolean)
  )] as string[]
}

export function getN5List(n1: string, n2: string, n3: string, n4: string): string[] {
  const prefix = n1 + ' > ' + n2 + ' > ' + n3 + ' > ' + n4 + ' > '
  return [...new Set(
    NAV_PATHS.filter(p => p.startsWith(prefix)).map(p => p.slice(prefix.length).split(' > ')[0]).filter(Boolean)
  )] as string[]
}
